import { PERMISSIONS, ROLES, type Permission } from "@/lib/constants";
import type { Role } from "@/types";

const OFFICE_READ_PERMISSIONS: Permission[] = [
  PERMISSIONS.VISITORS_READ,
  PERMISSIONS.MEETING_ROOMS_READ,
  PERMISSIONS.BOOKINGS_READ,
  PERMISSIONS.INVENTORY_READ,
  PERMISSIONS.STATIONERY_READ,
  PERMISSIONS.VENDORS_READ,
  PERMISSIONS.PURCHASE_READ,
  PERMISSIONS.EXPENSES_READ,
  PERMISSIONS.DASHBOARD_READ,
];

const OFFICE_WRITE_PERMISSIONS: Permission[] = [
  PERMISSIONS.VISITORS_WRITE,
  PERMISSIONS.BOOKINGS_WRITE,
  PERMISSIONS.INVENTORY_WRITE,
  PERMISSIONS.STATIONERY_WRITE,
  PERMISSIONS.PURCHASE_WRITE,
  PERMISSIONS.EXPENSES_WRITE,
];

const OFFICE_APPROVE_PERMISSIONS: Permission[] = [
  PERMISSIONS.VISITORS_APPROVE,
  PERMISSIONS.BOOKINGS_APPROVE,
  PERMISSIONS.PURCHASE_APPROVE,
];

export const PERMISSION_MATRIX: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.EMPLOYEES_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_WRITE,
    PERMISSIONS.LEAVES_APPROVE,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.SETTINGS_WRITE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.MEETING_ROOMS_READ,
    PERMISSIONS.MEETING_ROOMS_WRITE,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.VENDORS_WRITE,
    PERMISSIONS.ACTIVITY_READ,
    ...OFFICE_READ_PERMISSIONS,
    ...OFFICE_WRITE_PERMISSIONS,
    ...OFFICE_APPROVE_PERMISSIONS,
  ],
  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.EMPLOYEES_WRITE,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_WRITE,
    PERMISSIONS.LEAVES_APPROVE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.NOTIFICATIONS_WRITE,
    PERMISSIONS.VISITORS_READ,
    PERMISSIONS.VISITORS_WRITE,
    PERMISSIONS.VISITORS_APPROVE,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.ATTENDANCE_WRITE,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_APPROVE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    ...OFFICE_READ_PERMISSIONS,
    PERMISSIONS.VISITORS_WRITE,
    PERMISSIONS.BOOKINGS_WRITE,
    PERMISSIONS.PURCHASE_WRITE,
    ...OFFICE_APPROVE_PERMISSIONS,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [ROLES.FINANCE]: [
    PERMISSIONS.EMPLOYEES_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.PAYROLL_WRITE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.VENDORS_READ,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_APPROVE,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.EXPENSES_WRITE,
    PERMISSIONS.DASHBOARD_READ,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.LEAVES_READ,
    PERMISSIONS.LEAVES_WRITE,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.NOTIFICATIONS_READ,
    PERMISSIONS.VISITORS_READ,
    PERMISSIONS.VISITORS_WRITE,
    PERMISSIONS.MEETING_ROOMS_READ,
    PERMISSIONS.BOOKINGS_READ,
    PERMISSIONS.BOOKINGS_WRITE,
    PERMISSIONS.STATIONERY_READ,
    PERMISSIONS.PURCHASE_READ,
    PERMISSIONS.PURCHASE_WRITE,
    PERMISSIONS.DASHBOARD_READ,
  ],
};

export function getPermissionsForRole(role: Role): Permission[] {
  return PERMISSION_MATRIX[role] ?? [];
}

export function hasPermission(role: Role, permission: Permission): boolean {
  return getPermissionsForRole(role).includes(permission);
}

export function hasAnyPermission(
  role: Role,
  permissions: Permission[],
): boolean {
  const rolePermissions = getPermissionsForRole(role);
  return permissions.some((permission) => rolePermissions.includes(permission));
}

export function hasAllPermissions(
  role: Role,
  permissions: Permission[],
): boolean {
  const rolePermissions = getPermissionsForRole(role);
  return permissions.every((permission) => rolePermissions.includes(permission));
}
